routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;

use App\Http\Controllers\rumahsakit\PermohonanKalibrasiController;

use App\Http\Controllers\admin\Admincontroller;

// tambahan master 
use App\Http\Controllers\AlatController;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\KategorialatController;
// use App\Http\Controllers\HargaalatController;

Route::get('/', function () {
    return redirect()->route('home');
});


//permision kontroller  admin
Route::group(['middleware' => ['role:admin']], function() {
   //master
   // Route::get('/',[App\Http\Controllers\admin\Admincontroller::class, 'index'])->name('admin.page');
   Route::get('admin-page',[Admincontroller::class, 'index'])->name('admin.page');

   Route::get('admin-validasi',[Admincontroller::class, 'validasi'])->name('admin.validasi');
   Route::put('admin-validasi/{id}',[Admincontroller::class, 'validasi_admin'])->name('validasi_admin.validasi');
   Route::get('datas-bon',[Admincontroller::class, 'datas'])->name('bon.datas');
   //role
   Route::get('admin-roleuser',[App\Http\Controllers\admin\Admincontroller::class, 'admin_roleuser'])->name('role.admin_userrole');
   Route::get('admin-user',[App\Http\Controllers\admin\Admincontroller::class, 'admin_user'])->name('role.admin_user');
   // json
   Route::get('admin-user/{id}',[App\Http\Controllers\admin\Admincontroller::class, 'admin_user_id'])->name('role.admin_user_id');
   Route::post('admin-user/assign',[App\Http\Controllers\admin\Admincontroller::class, 'admin_user_assign'])->name('role.admin_user_assign');


   Route::resource('pegawai',App\Http\Controllers\admin\Pegawaicontroller::class);
   Route::resource('divisi',App\Http\Controllers\admin\Divisicontroller::class);
   Route::resource('barang',App\Http\Controllers\admin\Barangcontroller::class);
   Route::resource('jenis',App\Http\Controllers\admin\Jeniscontroller::class);
   Route::resource('pemasok',App\Http\Controllers\admin\PemasokController::class);
   Route::resource('satuan',App\Http\Controllers\admin\SatuanController::class);
   // transaksi barang masuk 
   Route::get('transaksi-masuk',[App\Http\Controllers\admin\Transaksimasukcontroller::class,'index'])->name('transaksimasuk');
   Route::post('transaksi-masuk',[App\Http\Controllers\admin\Transaksimasukcontroller::class,'store'])->name('transaksimasuk.store');
   Route::get('view-transaksi-masuk',[App\Http\Controllers\admin\Transaksimasukcontroller::class,'viewtransaksimasuk'])->name('transaksimasuk.view');
   //transaksi barang keluar
   Route::get('admin-transaksi-keluar',[App\Http\Controllers\admin\Transaksikeluarcontroller::class,'index'])->name('admin.transaksikeluar');
   //Laporan masuk
   Route::get('laporan-masuk',[App\Http\Controllers\admin\Laporanmasukcontroller::class,'index'])->name('laporanmasuk');
   Route::get('laporan-filtercari',[App\Http\Controllers\admin\Laporanmasukcontroller::class,'filtercari'])->name('laporanfiltercari');
   Route::post('laporan-masuk',[App\Http\Controllers\admin\Laporanmasukcontroller::class,'laporanmasukpost'])->name('laporanmasukpost');
  
   //Laporan keluar
   Route::get('laporan-keluar',[App\Http\Controllers\admin\Laporankeluarcontroller::class,'index'])->name('laporankeluar');
   Route::post('laporan-keluar',[App\Http\Controllers\admin\Laporankeluarcontroller::class,'laporanpost'])->name('laporanpost');

   //backup
   Route::get('admin-backup',[App\Http\Controllers\Backupcontrollermanual::class,'index'])->name('admin.backup');
   Route::get('admin-backup-mysql',[App\Http\Controllers\Backupcontrollermanual::class,'our_backup_database'])->name('our_backup_database');
});

//permision kontroller user
Route::group(['middleware' => ['role:user']], function() {
      // Route::get('/',[App\Http\Controllers\admin\Admincontroller::class, 'index'])->name('user.page');
   Route::get('user-page',[App\Http\Controllers\user\Usercontroller::class, 'index'])->name('user.page');

   // riwayat permohonan pegawai
   Route::get('permohonan-pegawai',[App\Http\Controllers\user\Usercontroller::class, 'getpermohonanpegawai'])->name('riwayat.permohonanpegawai');
   // end pp
   Route::get('pegawai-data',[App\Http\Controllers\user\Usercontroller::class, 'pegawaiData'])->name('pegawai.data');
   Route::post('pegawai-save',[App\Http\Controllers\user\Usercontroller::class, 'savePegawai'])->name('pegawai.save');

   Route::get('user-permohonan-kalibrasi',[App\Http\Controllers\user\Usercontroller::class, 'userKalibrasiRS'])->name('user.permohonankalrs');
   Route::get('user-permohonandl/{id}',[App\Http\Controllers\user\Usercontroller::class, 'cekpermohonandl'])->name('cekpermohonandl.get');
   Route::post('post-permohonan-kalibrasi',[App\Http\Controllers\user\Usercontroller::class, 'userkalibrasistore'])->name('user.userkalibrasistore');
   

   //pesan barang
   Route::get('user-pesan-barang',[App\Http\Controllers\user\UserPesanbarangcontroller::class, 'index'])->name('user.pesan');
   Route::post('simpan-pesan-barang',[App\Http\Controllers\user\UserPesanbarangcontroller::class, 'store'])->name('user.simpanbarang');
   Route::get('lihat-pesan-barang',[App\Http\Controllers\user\UserPesanbarangcontroller::class, 'lihatorder'])->name('user.lihatbarang');
   Route::get('lihat-pesan-barang/{id}',[App\Http\Controllers\user\UserPesanbarangcontroller::class, 'lihatdetailorder'])->name('user.lihatbarangdetail');
   
   // riwayat permohonan petugas jadwal 
   Route::get('/rumahsakit/riwayatpetugas',[PermohonanKalibrasiController::class,'riwayatpetugas'])->name('riwayatpetugas.index');

   // generate surat tugas 
   Route::post('generate-st',[PermohonanKalibrasiController::class,'cetakST'])->name('cetakST.index');
   
   // validasi
   Route::put('validasi/{id}',[App\Http\Controllers\user\UserPesanbarangcontroller::class,'validasi'])->name('user.validasi');
   //get status
   Route::get('get-status/{id}',[App\Http\Controllers\user\UserPesanbarangcontroller::class,'statusbon'])->name('user.statusbon');
   //laporan barang
   Route::get('laporan-barang-user',[App\Http\Controllers\user\UserPesanbarangcontroller::class, 'index'])->name('laporanbarang.user');
//approvement
});


Route::group(['middleware' => ['rumahsakit']], function () {
   // Rute-rute rumahsakit di sini
   Route::get('/rumahsakit', [App\Http\Controllers\rumahsakit\Rumahsakitcontroller::class, 'index'])->name('rumahsakit');
   Route::resource('/rumahsakit/permohonan',App\Http\Controllers\rumahsakit\PermohonanKalibrasiController::class);
   // Route::resource('/rumahsakit/transaksi-kalibrasi-rumahsakit',App\Http\Controllers\rumahsakit\TransaksiKalibrasiRumahsakitController::class);

   Route::get('/rumahsakit/data', [PermohonanKalibrasiController::class, 'getData'])->name('PermohonanKalibrasiController.data');
   Route::get('/rumahsakit/detail', [PermohonanKalibrasiController::class, 'getDetail'])->name('PermohonanKalibrasiController.detail');
   Route::get('/get-harga/{alat_id}', [PermohonanKalibrasiController::class, 'getHarga']);

   Route::get('/rumahsakit/riwayat',[PermohonanKalibrasiController::class,'riwayat'])->name('riwayat.index');

});
Auth::routes();

/*
Route::get('/rumahsakit', [App\Http\Controllers\rumahsakit\Rumahsakitcontroller::class, 'index'])->name('rumahsakit');
Route::resource('/rumahsakit/permohonan',App\Http\Controllers\rumahsakit\PermohonanKalibrasiController::class);
// Route::resource('/rumahsakit/transaksi-kalibrasi-rumahsakit',App\Http\Controllers\rumahsakit\TransaksiKalibrasiRumahsakitController::class);

Route::get('/rumahsakit/data', [PermohonanKalibrasiController::class, 'getData'])->name('PermohonanKalibrasiController.data');
Route::get('/rumahsakit/detail', [PermohonanKalibrasiController::class, 'getDetail'])->name('PermohonanKalibrasiController.detail');
Route::get('/get-harga/{alat_id}', [PermohonanKalibrasiController::class, 'getHarga']);
*/

// test
Route::get('/home', [HomeController::class, 'index'])->name('home');


// Route::group(['middleware' => ['auth']], function() {
//     Route::resource('roles', RoleController::class);
//     Route::resource('users', UserController::class);
//     Route::resource('products', ProductController::class);
// });

Route::resource('alats', AlatController::class);
Route::resource('provinsis', ProvinsiController::class);
Route::resource('kotas', KotaController::class);
Route::resource('kategorialats', KategorialatController::class);
// Route::resource('hargaalats', HargaalatController::class);

app/Http/Controllers/admin/PemasokController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Modelpemasok as pemasok;

class PemasokController extends Controller
{
    
    public function index()
    {
        $data = pemasok::orderBy('id','DESC')->get();
        // dd($data);
        return view('admin.pemasok.index',compact('data'));
    }

    
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
        $data = pemasok::create([
            'nama_pemasok' => $request->namapemasok,
            'no_telp' => $request->telp,
            'alamat_pemasok' => $request->alamat,
            // 'harga' => $request->harga
        ]);

        if($data){
            return redirect()->route('pemasok.index')->with(['success' => 'Data Berhasil Disimpan']);
        }else{
            return redirect()->route('pemasok.index')->with(['error' => 'Data Gagal Disimpan']);
        }

    }

    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(pemasok $pemasok)
    {
        return view('admin.pemasok.edit',compact('pemasok'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,pemasok $pemasok)
    {
        
        $update = $pemasok->update([
            'nama_pemasok' => $request->nama_pemasok,
            'no_telp'=>$request->no_telp,
            'alamat_pemasok' => $request->alamat_pemasok,
        ]); 
        if($update){
            return redirect()->route('pemasok.index')->with(['success' => 'Data Berhasil Diubah!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pemasok/edit.blade.php
@extends('admin.appadmin')
@section('konten')
<div class="row">
   <div class="col-md-6">
      <div class="card" >
         <div class="card-body">
            <h5 class="card-title">Form Penyedia Edit</h5>
            <form action="{{ route('pemasok.update',$pemasok->id) }}" method="POST">
               {{ csrf_field() }}
               @method('PUT')
               {{-- <input class="form-control form-control-sm mb-2" type="text" name="barang_id" value="{{ $barang->id }}" aria-label=".form-control-sm example"> --}}
               <input class="form-control form-control-sm mb-2" type="text" name="nama_pemasok" value="{{ $pemasok->nama_pemasok }}" aria-label=".form-control-sm example">
               <input class="form-control form-control-sm mb-2" type="text" name="no_telp" value="{{ $pemasok->no_telp }}" aria-label=".form-control-sm example">
               <input class="form-control form-control-sm mb-2" type="text" name="alamat_pemasok" value="{{ $pemasok->alamat_pemasok }}" aria-label=".form-control-sm example">
               <input type="submit" class="btn btn-sm btn-primary" value="SIMPAN">
            </form>
         </div>
      </div>
   </div>
</div>

@endsection
@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
@endsection

resources/views/admin/pemasok/index.blade.php
@extends('admin.appadmin')
@section('konten')
<div class="row">
   <div class="col-md-6">
      <div class="card" >
         <div class="card-body">
            <h5 class="card-title">Form Pemasok</h5>
            <form action="{{ route('pemasok.store') }}" method="POST">
               {{ csrf_field() }}
               <input class="form-control form-control-sm mb-2" type="text" name="namapemasok" placeholder="Nama Pemasok" aria-label=".form-control-sm example">
               <input class="form-control form-control-sm mb-2" type="text" name="telp" placeholder="Phone (contoh : 08213999112X)" aria-label=".form-control-sm example">
               <input class="form-control form-control-sm mb-2" type="text" name="alamat" placeholder="Alamat Lengkap" aria-label=".form-control-sm example">
               <input type="submit" class="btn btn-sm btn-primary" value="SIMPAN">
            </form>
         </div>
      </div>
   </div>
</div>
<div class="row">
   <div class="col-md-12">
      <div class="card">
         <div class="card-body">
            <table class="table caption-top" id="myTable">
               <caption>Tabel Pemasok</caption>
               <thead>
                  <tr>
                     <th scope="col">NO</th>
                     <th scope="col">Nama Pemasok</th>
                     <th scope="col">No Telp</th>
                     <th scope="col">Alamat Lengkap</th>
                     <th scope="col"></th>
                  </tr>
               </thead>
               <tbody>
                <?php $i=1?>
                @foreach ($data as $item)
                  <tr>
                     <th scope="row">{{ $i++ }}</th>
                     <td>{{ $item->nama_pemasok }}</td>
                     <td>{{ $item->no_telp }}</td>
                     <td>{{ $item->alamat_pemasok }}</td>
                     <td>
                      <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('pemasok.destroy', $item->id) }}" method="POST">
                                            <a href="{{ route('pemasok.edit', $item->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                     </td>
                  </tr>
                @endforeach
                  
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>
@endsection
@section('js')
<link href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.dataTables.min.css" rel="stylesheet" media="screen">
<link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet" media="screen">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
// alert("test");
$('#myTable').dataTable();
})
// table = new DataTable('#myTable');
   @if(session()->has('success'))
   toastr.success('{{ session('success') }}', 'BERHASIL!');
   @elseif(session()->has('error'))
     toastr.error('{{ session('error') }}', 'GAGAL!');
   @endif
</script>
@endsection